CREATE USER pentaho WITH PASSWORD 'niedw';
  CREATE DATABASE stage;
  CREATE DATABASE target;
  GRANT ALL PRIVILEGES ON DATABASE stage TO pentaho;
  GRANT ALL PRIVILEGES ON DATABASE target TO pentaho;
  ALTER USER pentaho WITH SUPERUSER;